import Head from "next/head";
import Image from "next/image";
import ShopLinksGroup from "../components/ShopLinksGroup";
import SectionAbout from "../components/SectionAbout";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionBanner />
        <div className="max-w-[1110px] px-[24px] mx-auto">
          <ShopLinksGroup />
          <SectionProducts />
          <SectionAbout />
        </div>
      </main>
    </div>
  );
}

const SectionBanner = () => {
  return (
    <section className="relative mx-auto text-[white] overflow-hidden mb-[96px]">
      <div className="w-screen bg-smoke">
        <div className="relative">
          <picture>
            <source
              media="(min-width: 992px)"
              srcSet="/images/desktop/image-hero.jpg"
            />
            <source
              media="(min-width: 768px)"
              srcSet="/images/tablet/image-header.jpg"
            />
            <img src="images/mobile/image-header.jpg" alt="banner" />
          </picture>
        </div>
      </div>

      <div className="absolute z-[1] w-full h-[720px]">
        <div className="relative max-w-[1110px] w-full h-full mx-auto">
          <div className="max-w-[379px] absolute left-[50%] lg:left-0 top-[50%] translate-x-[-50%] lg:translate-x-0 translate-y-[-50%] flex flex-col justify-center items-center z-10 text-center">
            <span className="relative mb-[16px] text-[14px] tracking-[10px] opacity-75">
              NEW PRODUCT
            </span>
            <h1 className="md:text-[56px] md:leading-[58px]">
              XX99 Mark II Headphones
            </h1>
            <p className="text-white">
              Experience natural, lifelike audio and exceptional build quality
              made for the passionate music enthusiast.
            </p>
            <Link href={"product/xx99-mark-two-headphones"}>
              <button className="btn orange">SEE PRODUCT</button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

const SectionProducts = () => {
  return (
    <section>
      <div className="featured-product overflow-hidden">
        <div className="relative lg:absolute lg:bottom-[-49px] lg:left-[117px] w-[172px] h-[207px] lg:w-[410px] lg:h-[493px] mx-auto mb-[32px]">
          <Image
            src="/images/image-speaker-zx9.png"
            layout="fill"
            objectFit="contain"
            alt="zx9 speaker"
          />
        </div>
        <div className="max-w-[349px] lg:absolute lg:right-[95px] lg:top-[50%] lg:translate-y-[-50%] flex flex-col justify-center lg:justify-start items-center lg:items-start">
          <h2 className="text-white lg:text-left">
            ZX9
            <br /> SPEAKER
          </h2>
          <p className="text-white lg:text-left">
            Upgrade to premium speakers that are phenomenally built to deliver
            truly remarkable sound.
          </p>
          <Link href="product/zx9-speaker">
            <button className="btn black">SEE PRODUCT</button>
          </Link>
        </div>
      </div>

      <div className="relative w-full my-[24px] rounded-[8px] overflow-hidden">
        <picture>
          <source
            media="(min-width: 992px)"
            srcSet="/images/desktop/image-speaker-zx7.jpg"
          />
          <source
            media="(min-width: 768px)"
            srcSet="/images/tablet/image-speaker-zx7.jpg"
          />
          <img
            className="w-full object-cover"
            src="/images/mobile/image-speaker-zx7.jpg"
            alt="zx7 speaker"
          />
        </picture>

        <div className="absolute top-[50%] left-[24px] translate-y-[-50%]">
          <h3 className="text-[28px] tracking-[2px]">ZX7 SPEAKER</h3>
          <Link href="product/zx7-speaker">
            <button className="btn transparent mt-[32px]">SEE PRODUCT</button>
          </Link>
        </div>
      </div>

      <div className="w-full grid md:grid-cols-2 items-center gap-[12px]">
        <div className="relative w-full h-[200px] md:h-[320px] my-[24px] rounded-[8px] overflow-hidden">
          <Image
            src="/images/image-earphones-yx1.jpg"
            layout="fill"
            objectFit="cover"
            alt="zx9 speaker"
          />
        </div>

        <div className="w-full flex flex-col justify-center items-start h-[200px] md:h-[320px] bg-lightGray rounded-[8px] px-[24px] overflow-hidden">
          <h4 className="mb-[32px] text-[32px] tracking-[2px]">
            YX1 EARPHONES
          </h4>
          <Link href="product/yx1-earphones">
            <button className="btn transparent">SEE PRODUCT</button>
          </Link>
        </div>
      </div>
    </section>
  );
};
